steps:
  - id: Package image
    name: gcr.io/cloud-builders/npm
    args: [ 'install' ]

  - id: Execute test
    name: gcr.io/cloud-builders/npm
    entrypoint: bash
    args:
      - -c
      - |
        npm install @capacitor/core
        npm install @capacitor/cli
        npm run build
        npx cap sync
        


substitutions:
  _IMAGE_NAME: mobile-app
