steps:
  - id: Package image
    name: gcr.io/cloud-builders/npm
    args: [ 'install' ]
    volumes:
      - name: 'myvolume'
        path: '/persistent_volume'
  - id: Execute test
    name: gcr.io/cloud-builders/npm
    entrypoint: bash
    args:
      - -c
      - |
        npm i xlsx --save
        npm install @capacitor/core
        npm install @capacitor/cli
        npm run build
        npx cap sync
    volumes:
      - name: 'myvolume'
        path: '/persistent_volume'
  - name: 'gcr.io/cloud-builders/git'
    id: Clone env repository
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        ls
    volumes:
      - name: 'myvolume'
        path: '/persistent_volume'


substitutions:
  _IMAGE_NAME: mobile-app
