steps:
  - id: Package image
    name: gcr.io/cloud-builders/npm
    args: [ 'install' ]
  - id: Package image
    name: gcr.io/cloud-builders/npm
    args: [ 'coverage' ]
    volumes:
      - name: 'myvolume'
        path: '/persistent_volume'
  - name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
    args:
      - '-Dsonar.host.url=http://34.67.142.84:9001'
      - '-Dsonar.login=admin'
      - '-Dsonar.password=admin123'
      - '-Dsonar.projectKey=sport-app-mobie'
      - '-Dsonar.projectName=sport-app-mobie'
      - '-Dsonar.projectVersion=1.25.4'
      - '-Dsonar.sourceEncoding=UTF-8'
      - '-Dsonar.sources=src'
      - '-Dsonar.test.exclusions=**/node_modules/**'
      - '-Dsonar.test.exclusions=**/src/app/**'
      - '-Dsonar.test.exclusions=**/src/assets/**'
      - '-Dsonar.test.exclusions=**/src/constants/**'
      - '-Dsonar.test.exclusions=**/src/helper/**'
      - '-Dsonar.test.exclusions=**/src/models/**'
      - '-Dsonar.test.exclusions=**/src/styles/**'
      - '-Dsonar.test.exclusions=**/src/test/**'
      - '-Dsonar.test=src'
      - '-Dsonar.typescript.lcov.reportPaths=coverage/SportApp/lcov.info'
  - id: Execute test
    name: gcr.io/cloud-builders/npm
    entrypoint: bash
    args:
      - -c
      - |
        npm i xlsx --save
        npm install @capacitor/core
        npm install @capacitor/cli
        npm install @capacitor/android
        npx cap add android
        npm run build
        npx cap sync
    volumes:
      - name: 'myvolume'
        path: '/persistent_volume'
#  - name: gradle:5.6.2-jdk8
#    entrypoint: bash
#    args:
#      - -c
#      - |
#        cd android/
#        gradlew installDebug
#    volumes:
#      - name: 'myvolume'
#        path: '/persistent_volume'


substitutions:
  _IMAGE_NAME: mobile-app
