steps:
  - id: Package image
    name: gcr.io/cloud-builders/npm
    args: [ 'install' ]

  - id: Execute test
    name: gcr.io/cloud-builders/npm
    entrypoint: bash
    args:
      - -c
      - |
        npm i xlsx --save
        npm install @capacitor/core
        npm install @capacitor/cli
        npm run build
        npx cap sync

  - name: gradle:5.6.2-jdk8
    entrypoint: bash
    args:
      - -c
      - |
        ls 

  - name: gradle:5.6.2-jdk8
    entrypoint: gradle
    args: ['assemble']



substitutions:
  _IMAGE_NAME: mobile-app
