steps:
  - id: Package image
    name: gcr.io/cloud-builders/npm
    args: [ 'install' ]

  - id: Execute test
    name: gcr.io/cloud-builders/npm
    entrypoint: bash
    args:
      - -c
      - |
        npm i xlsx --save
        npm install @capacitor/core
        npm install @capacitor/cli
        npm run build
        npx cap sync

  - name: ubuntu
    entrypoint: bash
    args:
      - -c
      - |
        echo "First we saved " ls
        echo "cd.." cd ..





substitutions:
  _IMAGE_NAME: mobile-app
