steps:
  - id: Package image
    name: gcr.io/cloud-builders/npm
    args: [ install ]

  - id: Execute test
    name: gcr.io/cloud-builders/npm
    args: [ test ]

  - id: Sonar Analysis
    name: gcr.io/cloud-builders/npm
    args: [ 'run','sonar' ]

  - id: Docker Build
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-f','Dockerfile', '-t','gcr.io/$PROJECT_ID/${REPO_NAME}','.' ]

  - id: Docker push
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'push','gcr.io/$PROJECT_ID/${REPO_NAME}:v0' ]

  - id: Deploy Cloud Run
    name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'run','deploy','${_IMAGE_NAME}',
            '--image','gcr.io/$PROJECT_ID/${REPO_NAME}:${TAG_NAME}',
            '--allow-unauthenticated',
            '--min-instances=1',
            '--max-instances=2',
            '--region=us-central1',
            '--project=$PROJECT_ID' ]
substitutions:
  _IMAGE_NAME: miso-front-web
