steps:
  - id: Package image
    name: gcr.io/cloud-builders/npm
    args: [ 'install' ]
    volumes:
      - name: 'myvolume'
        path: '/persistent_volume'
  - id: Execute test
    name: gcr.io/cloud-builders/npm
    entrypoint: bash
    args:
      - -c
      - |
        npm i xlsx --save
        npm install @capacitor/core
        npm install @capacitor/cli
        npm install @capacitor/android
        npx cap add android
        npm run build
        npx cap sync
    volumes:
      - name: 'myvolume'
        path: '/persistent_volume'
  - name: 'gcr.io/cloud-builders/docker'
    volumes:
      - name: 'myvolume'
        path: '/persistent_volume'
    args: ['ls','run', '-v', 'myvolume:/home/app', '--rm', 'gcr.io/fullstackgcp/gradle', '/bin/sh', '-c', 'cd /home/app && ./gradlew clean assembleDebug']


substitutions:
  _IMAGE_NAME: mobile-app
